### ISSUE TITLE
Hugh amount of files upload problem 

### ISSUE THREAD

**Issue by JanStuden** [MPDL/upverse#10]
Testserver: https://qa-edmond2.mpdl.mpg.de/dataverse/edmond
Browser: ff / Windows
Testdate: 09.03.2023
User: user

Actions: -> "Choose Folders" -> "Windows explorer opens" -> Choose folder with 1900 files -> upload them

Observation: only 1000 files uploaded even when it says in the warning message that the upload of 2000 files is possible:
![image](https://user-images.githubusercontent.com/94779102/224305027-b32bfadc-ee39-4b06-8d5c-2e7593d44d6a.png)
![image](https://user-images.githubusercontent.com/94779102/224305145-68638c5a-6140-40cc-ae70-c2e6eda4ad55.png)

Expected result: after the warning message I expected that still all 1940 files would be uploaded

**Comment by helkv** [comment]
Version: [v1.0.0](https://github.com/MPDL/upverse/releases/tag/v1.0.0) (https://github.com/MPDL/upverse/commit/c835405ed66050556a6a0810c2d466e73c88d466)
OS: Linux & Mac
Testdate: 20.07.2023
User: User
Action: Upload folders with 500, 1001 and 2001 files
Test result: ok
