### ISSUE TITLE
Selected Files are no longer displayed if Destination dataset changes

### ISSUE THREAD

**Issue by helkv** [MPDL/upverse#12]
Testserver: https://qa-edmond2.mpdl.mpg.de
Browser: ff / Linux
Testdate: 08./09.03.2023
User: User
Observation:
1. Select a Destination dataset
2. Choose Folders -> Select a Folder
3. The selected Files are displayed
4. Select another Destination dataset
5. The selected Files are NOT displayed, but are still selected! 

Expected result: Selected Files stay visible if the Destination dataset changes

**Comment by hofmannc** [comment]
Server: upverse-1.0.0.Setup.exe - build package release #55
OS: Windows
Testdate: 29.06.2023
User: Hofmann, Catherina
Test result: ok
