### ISSUE TITLE
Enhancement: Make new data set available immediately (in destination data set) 

### ISSUE THREAD

**Issue by hofmannc** [MPDL/upverse#14]
Server: upverse-1.0.0.Setup.exe - buttons issue fixed https://github.com/MPDL/upverse/issues/13
OS: Windows
Testdate: 24.04.2023
User: Hofmann, Catherina

Action: -> log in upverse -> log in dataverse -> create new data set -> select destination data set in upverse ->
Observation: -> new data set is not available in listing -  I have to exit and re-log in to have it displayed in drop down menue
Expected result: If I create a new data set in Dataverse, the data set is available in listing immediately or by pushing a re-fresh button

**Comment by hofmannc** [comment]
Server: upverse-1.0.0.Setup.exe - build package release #55
OS: Windows
Testdate: 29.06.2023
User: Hofmann, Catherina
Test result: ok

**Comment by helkv** [comment]
Version: [v1.0.0](https://github.com/MPDL/upverse/releases/tag/v1.0.0) (https://github.com/MPDL/upverse/commit/c835405ed66050556a6a0810c2d466e73c88d466)
OS: Linux & Mac
Testdate: 20.07.2023
User: User
Test result: ok
