### ISSUE TITLE
Windows: "Cancel" -> upload process results in frozen item list

### ISSUE THREAD

**Issue by hofmannc** [MPDL/upverse#21]
Server: upverse-1.0.0.Setup.exe - build package release #55
OS: Windows
Testdate: 29.06.2023
User: Hofmann, Catherina

Actions: Select destination data set -> select files or folder -> "Upload" -> while upload is running -> "Clear" ->

Observation: View is freezing, see screenshot. To be able to start a new upload process it is neccesary to Exit Upverse 
![image](https://github.com/MPDL/upverse/assets/14921701/ffe83c71-7480-403e-beb2-b39109902a6a)

Expected result: After canceling, items are deleted from view and I can start a new upload process

**Comment by vilarodr** [comment]
Item list clean and buttons activate fixed.

**Comment by hofmannc** [comment]
Server: upverse-1.0.0.Setup.exe - build package release #61
OS: Mac
Testdate: 03.07.2023
User: Hofmann, Catherina
Test result: NOK, issue seems to persist for Mac

**Comment by helkv** [comment]
Version: [v1.0.0](https://github.com/MPDL/upverse/releases/tag/v1.0.0) (https://github.com/MPDL/upverse/commit/c835405ed66050556a6a0810c2d466e73c88d466)
OS: Mac
Testdate: 19.07.2023
User: User
Test result: ok
