### ISSUE TITLE
„Invalid input“ error, if Filepath is empty

### ISSUE THREAD

**Issue by helkv** [MPDL/upverse#23]
Version: [v1.0.0](https://github.com/MPDL/upverse/releases/tag/v1.0.0) (8fa1714)
OS: Linux
Browser: Firefox
Testdate: 29./30.06.2023
User: User

An „Invalid input“ error message is displayed, if you try to edit the Description or the File Path while the File Path is empty.

Actions:
1. Select destination data set
2. Select a file
3. Add a description (while the 'File 'Path' input filed is still empty)
4. Click anywhere else
5. An „Invalid input“ error is displayed

The same „Invalid input“ error is displayed if an existing File Path is removed (e.g. when using the Folder upload).

**Comment by hofmannc** [comment]
Server: upverse-1.0.0.Setup.exe - build package release #61
OS: Windows
Testdate: 04.07.2023
User: Hofmann, Catherina
Observation:


    1. Select destination data set
    2. Select a file
    3. Add a description (while the 'File 'Path' input filed is still empty)
    4.  --> description only contains valid characters
    5. Click anywhere else
    6. An „Invalid input“ error is displayed
-> both entry fields are not editable anymore, but file can be deleted from list

**Comment by vilarodr** [comment]
Bug fixed, filepath field was set as required for item changes

**Comment by hofmannc** [comment]
Server: upverse-1.0.0.Setup.exe - build package release #62
OS: Mac
Testdate: 05.07.2023
User: Hofmann, Catherina
Test result: ok
