### ISSUE TITLE
Linux: Select Files/Folders dialog opens in background

### ISSUE THREAD

**Issue by helkv** [MPDL/upverse#24]
Version: [v1.0.0](https://github.com/MPDL/upverse/releases/tag/v1.0.0) (https://github.com/MPDL/upverse/commit/8fa17145c664c4c568de1b9d8fbc5b8044d5b9ca)
OS: Linux
Browser: Firefox
Testdate: 29./30.06.2023
User: User

If the Files/Folders dialog is opened a second time, the dialog opens behind the Upverse main window and a system notification is displayed "Upverse <<>> ist bereit".

Actions:
1. Select destination data set
2. Click 'Files' or 'Folders'
3. The Files/Folders dialog is correctly displayed in the front
4. (Select some files or folders)
5. Click 'Files' or 'Folders' a second time
6. The Files/Folders dialog opens behind the Upverse main window and a system notification is displayed "Upverse <<>> ist bereit".

**Comment by hofmannc** [comment]
Server: upverse-1.0.0.Setup.exe - build package release #61
OS: Windows
Testdate: 04.07.2023
User: Hofmann, Catherina
Test result: i cannot reproduce this for Windows

**Comment by vilarodr** [comment]
Its a Electron bug on Linux reported one year ago but not yet fixed, see:

https://github.com/electron/electron/issues/32857

Perhaps it will be solved on future Electron releases, we will be aware.
