### ISSUE TITLE
Upload # in file name

### ISSUE THREAD

**Issue by yvgrossmann** [MPDL/upverse#28]
When you upload a file with a # in the file name Upverse give a positive feedback. Nevertheless the file will not be uploaded.

**Comment by vilarodr** [comment]
Bug fixed.

**Comment by vilarodr** [comment]
File names are checked before they comes to the to_upload list of files and in case of fail, the user will be noticed about in order to give him the optionto  rename the files, otherwise all files with wrong name where excluded from upload.
