### ISSUE TITLE
Upload Zip-file: Error Message

### ISSUE THREAD

**Issue by hofmannc** [MPDL/upverse#31]
Von: Bibliothek MPIKG <[biblio@mpikg.mpg.de](mailto:biblio@mpikg.mpg.de)> 
Gesendet: Donnerstag, 11. Januar 2024 09:21
An: Grossmann, Yves Vincent <[grossmann@mpdl.mpg.de](mailto:grossmann@mpdl.mpg.de)>
Betreff: AW: Download großer Datenmengen von Edmond
![Edmond](https://github.com/MPDL/upverse/assets/14921701/9a8f45d6-4994-4fb8-a6d8-d86f05f0f14a)

Lieber Yves,

[...]

Ich habe auch schon die nächste Frage, diesmal wieder zum Upload.
Hier erscheint ein Fehler beim Upload von Zip-Dateien, wie im angehängten Bild angezeigt. Könnt Ihr uns da bitte auch weiterhelfen? Dankeschön!

Viele Grüße
Annette

**Comment by hofmannc** [comment]
Testserver: qa edmond/upverse
Browser: ff
Version: 16.01.2024
User: admin/user

Result: cannot reproduce given error message. 
The first time I uploaded the folder containing µ, the "keine Sonderzeichen erlaubt" Message came up

from the second time on: -> "folder" -> "upload" -> Message: "1 files to upload, 0 fails
1 files uploaded to doi:10.15771/3.3VMXTN" -> but no folder displayed in dataset.

**Comment by hofmannc** [comment]
Testserver: QA.edmond 
Browser: ff
Version: build package release #74, windows
User: Admin
Result: OK, -> "folder" -> "Testvariante_µ_240115" ->"upload" -> error message displayed

**Comment by hofmannc** [comment]
Testserver: QA.edmond
Browser: ff
Version: build package release #76, windows
User: Admin
Result: OK

**Comment by vilarodr** [comment]
Fixed on previous release.

**Comment by helkv** [comment]
Version: [v1.3.0](https://github.com/MPDL/upverse/releases/tag/v1.3.0) (https://github.com/MPDL/upverse/commit/116eb01a4cb54889b7f22c8697c19968929f4eb3)
OS: Linux
Testdate: 03.09.2024
User: User
Test result: ok
