### ISSUE TITLE
Upload of over 2000 files seems to be possible

### ISSUE THREAD

**Issue by hofmannc** [MPDL/upverse#32]
Testserver: qa edmond/upverse
Browser: ff
Version: 01.02.2024
User: admin/user
Actions: 
select data set -> "files" select files -> "folders" select folders -> a total of over 2000 files is selected -> "upload" ->
Observation: 
files are successfully uploaded to dataverse
![image](https://github.com/MPDL/upverse/assets/14921701/fc77eaff-1e2e-4fbe-8cb8-cd2ffb0b8ea7)

Expected result: User gent an information that the limit is exceeded and upload is not possible

**Comment by hofmannc** [comment]
Testserver: QA.edmond
Browser: ff
Version: build package release #76, windows
User: Admin
Result: OK, error message is correctly displayed 

--> 2 questions:
Could message text be changed to e.g. "Maximum number of files exceeded"?
Should the amount of allowed files be mentioned?
--> t.b.d. in Jour Fixe

**Comment by hofmannc** [comment]
Testserver: QA.edmond
Browser: ff
Version: Version 1.3.0 / windows
User: Admin
Result: OK, error message is displayed, but no reason given, t.b.d.
![grafik](https://github.com/user-attachments/assets/c7657139-cdd7-4ff2-9398-7cdb5c1c8f49)

**Comment by vilarodr** [comment]
First message comes from server: Request for direct upload rejected, the reason is given in the second message. 
The existence of two different messages for the same alert may confuse the user, the first message should not be displayed. It will be fixed as soon as possible.
