### ISSUE TITLE
Windows: Selected data set gets de-selected by clicking "files"

### ISSUE THREAD

**Issue by hofmannc** [MPDL/upverse#34]
Testserver: qa edmond/upverse
Browser: ff
OS: Windows
Version: 03.04.2024
User: admin/user
Actions:
enter Upverse -> select data set -> "files" ->
Observation:
-> Selected data set is removed from selection bar and user has to select data set again -> with the second try, the upload process can be completed as usual.
This only seems to be relevant for windows, and it is not in every case reproducible, but happens quite often, especially immediately after entering upverse, sometimes later, but there is no recognisable pattern.

Expected result: data set stays selected during the upload process.

**Comment by hofmannc** [comment]
Testserver: QA.edmond
Browser: ff
Version: 1.2, build package release #83, windows
User: Admin
Result: OK

**Comment by hofmannc** [comment]
Testserver: QA.edmond
Browser: ff
Version: 1.3.0 windows
User: Admin
Result: OK, not reproducible for windows

**Comment by vilarodr** [comment]
Bug fixed in previous version.

**Comment by helkv** [comment]
Version: [v1.3.0](https://github.com/MPDL/upverse/releases/tag/v1.3.0) (https://github.com/MPDL/upverse/commit/116eb01a4cb54889b7f22c8697c19968929f4eb3)
OS: Linux
Testserver: QA.edmond
Testdate: 03.09.2024
User: User
Test result: ok
