### ISSUE TITLE
Files of 200GB size create an error

### ISSUE THREAD

**Issue by StephanJanosch** [MPDL/upverse#37]
I used version 1.2 

![Screenshot 2024-06-27 at 14 30 22](https://github.com/MPDL/upverse/assets/11651596/f0a79f45-9d36-4e5a-895a-2bc30d820f79)

**Comment by vilarodr** [comment]
Pre-release version 1.3 available that fixes this issue.

**Comment by StephanJanosch** [comment]
😀

**Comment by helkv** [comment]
Version: [v1.3.0](https://github.com/MPDL/upverse/releases/tag/v1.3.0) (https://github.com/MPDL/upverse/commit/116eb01a4cb54889b7f22c8697c19968929f4eb3)
OS: Linux
Testserver: QA.edmond
Testdate: 05.09.2024
User: User
Test result: ok
