### ISSUE TITLE
Usability Observations

### ISSUE THREAD

**Issue by hofmannc** [MPDL/upverse#9]
List of UI and Usability Observations:

---

1. Title: **Prevent Uploadprocess until destination data set is not selected**
Testserver: https://qa-edmond2.mpdl.mpg.de/dataverse/edmond
Browser: ff / Windows
Testdate: 08./09.03.2023
User: user
Observation: User forgets to select a "Destination data set" -> "Choose folders" -> "Upload" -> "Notification on successful upload"
Expected result: But where are the files uploaded to? It would be nice if somehow it is prevented making an upload with out having selected a destination data set, e.g. by blocking "choose folders" 

Server: upverse-1.0.0.Setup.exe - buttons issue fixed https://github.com/MPDL/upverse/issues/13
OS: Windows
Testdate: 24.04.2023
User: Hofmann, Catherina
Test result: ok

Version: [v1.0.0](https://github.com/MPDL/upverse/releases/tag/v1.0.0) (https://github.com/MPDL/upverse/commit/c835405ed66050556a6a0810c2d466e73c88d466)
OS: Linux & Mac
Testdate: 20.07.2023
User: User
Test result: ok

---

2. Title: **Make uploaded folder and destination data set in notification explicit**
Testserver: https://qa-edmond2.mpdl.mpg.de/dataverse/edmond
Browser: ff / Windows
Testdate: 08./09.03.2023
User: user
Observation: 
![grafik](https://user-images.githubusercontent.com/14921701/224015654-7bc5484a-2a21-4f41-8aa9-4c8f194af454.png)
Expected result: If would be useful for user to make the folder and data set explicit in the notification.

Server: upverse-1.0.0.Setup.exe - buttons issue fixed https://github.com/MPDL/upverse/issues/13
OS: Windows
Testdate: 24.04.2023
User: Hofmann, Catherina
Test result: ok

---

3. Title: **Add Throbber for 'Connect'**
Testserver: https://qa-edmond2.mpdl.mpg.de
Browser: ff / Linux
Testdate: 08./09.03.2023
User: user
Observation: When clicking 'Connect' it takes some time until the Datasets are loaded, if a user has many Datasets
Expected result: A Throbber is displayed when connecting

Server: upverse-1.0.0.Setup.exe - buttons issue fixed https://github.com/MPDL/upverse/issues/13
OS: Windows
Testdate: 24.04.2023
User: Hofmann, Catherina
Test result: ok

---

4.  Title: **Add Cancel for Upload**
     Testserver: https://qa-edmond2.mpdl.mpg.de/
     Testdate: 09.03.2023
     User: user
     Observation: When uploading a large file or many small files, there is no way to cancel or stop the upload

Server: upverse-1.0.0.Setup.exe - buttons issue fixed https://github.com/MPDL/upverse/issues/13
OS: Windows
Testdate: 24.04.2023
User: Hofmann, Catherina
Test result: ok

Version: [v1.0.0](https://github.com/MPDL/upverse/releases/tag/v1.0.0) (https://github.com/MPDL/upverse/commit/c835405ed66050556a6a0810c2d466e73c88d466)
OS: Linux & Mac
Testdate: 19.07.2023
User: User
Test result: ok

---

5.  Title: **Disable Choosing of new folders while uploading other folder**
     Testserver: https://qa-edmond2.mpdl.mpg.de/
     Testdate: 09.03.2023
     User: user
     Observation:  When uploading folders, the option to add more folders is enabled, but when you add them, they are not 
     uploaded at the end
     Expected result: Either adding folder(s) during the upload of other folder(s) is disabled or the added folder(s) during the 
     upload are uploaded as well    

Server: upverse-1.0.0.Setup.exe - buttons issue fixed https://github.com/MPDL/upverse/issues/13
OS: Windows
Testdate: 24.04.2023
User: Hofmann, Catherina
Test result: ok 

Version: [v1.0.0](https://github.com/MPDL/upverse/releases/tag/v1.0.0) (https://github.com/MPDL/upverse/commit/c835405ed66050556a6a0810c2d466e73c88d466)
OS: Linux & Mac
Testdate: 20.07.2023
User: User
Test result: ok

---

6. Title: **Remove the "Developer" Tab for the final Upverse version**

Server: upverse-1.0.0.Setup.exe - build package release #55
OS: Windows
Testdate: 29.06.2023
User: Hofmann, Catherina
Test result: ok

Version: [v1.0.0](https://github.com/MPDL/upverse/releases/tag/v1.0.0) (https://github.com/MPDL/upverse/commit/c835405ed66050556a6a0810c2d466e73c88d466)
OS: Linux & Mac
Testdate: 20.07.2023
User: User
Test result: ok

---

7. Title: **Add a description (or watermark) for the API Token and API URL input fields**

Server: upverse-1.0.0.Setup.exe - build package release #55
OS: Windows
Testdate: 29.06.2023
User: Hofmann, Catherina
Test result: ok

Version: [v1.0.0](https://github.com/MPDL/upverse/releases/tag/v1.0.0) (https://github.com/MPDL/upverse/commit/c835405ed66050556a6a0810c2d466e73c88d466)
OS: Linux & Mac
Testdate: 20.07.2023
User: User
Test result: ok

---

8. Title: **Change the button label in the "Choose Folders" menu from "Hochladen" to "Öffnen"**
obsolete

---

9. Title: **(Question) Can the size of the executables be reduced (compressed)?**

---

10. Title: **SavaScript error when testing an invalid Repository URL**
Observation:
![Bildschirmfoto vom 2023-07-03 10-05-51](https://github.com/MPDL/upverse/assets/38949722/bd02fe32-8059-4a60-a7d9-f2332c65a070)

Version: [v1.0.0](https://github.com/MPDL/upverse/releases/tag/v1.0.0) (c835405)
OS: Linux
Browser: Firefox
Testdate: 18.07.2023
User: User
Test result: ok

---

12. Title: **Remove the "Edit" Tab?**
Observation: 
![Bildschirmfoto vom 2023-07-03 10-09-05](https://github.com/MPDL/upverse/assets/38949722/84931354-7c19-4b64-883c-f9876ad779a9)

**Comment by vilarodr** [comment]
Issue 9 fixed with Notificacion: Invalid URL!

Point 10 is needed to copy & paste data from other apps.
